In [5]:
# Generate Gaussian Data for 2 Classes

import numpy as np

np.random.seed(0)

n = 400
half = n // 2

# Class 0 centered at (-2, -2)
class0 = np.random.randn(half, 2) + np.array([-2, -2])

# Class 1 centered at (2, 2)
class1 = np.random.randn(half, 2) + np.array([2, 2])

X = np.vstack((class0, class1))
y = np.vstack((np.zeros((half,1)), np.ones((half,1))))
print("X shape:", X.shape) # (400, 2)
print("y shape:", y.shape) # (400, 1)
print("First 5 samples:\n", X[:5])
print("First 5 labels:\n", y[:5])

X shape: (400, 2)
y shape: (400, 1)
First 5 samples:
 [[-0.23594765 -1.59984279]
 [-1.02126202  0.2408932 ]
 [-0.13244201 -2.97727788]
 [-1.04991158 -2.15135721]
 [-2.10321885 -1.5894015 ]]
First 5 labels:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [6]:
# Generate Gaussian Data with Different Covariances

mean0 = [-2, -2]
cov0 = [[1, 0.8], [0.8, 1]]

mean1 = [2, 2]
cov1 = [[1, -0.6], [-0.6, 1]]

class0 = np.random.multivariate_normal(mean0, cov0, 200)
class1 = np.random.multivariate_normal(mean1, cov1, 200)

X = np.vstack((class0, class1))
y = np.vstack((np.zeros((200,1)), np.ones((200,1))))

print("X shape:", X.shape) # (400, 2)
print("y shape:", y.shape) # (400, 1)
print("First 5 samples:\n", X[:5])
print("First 5 labels:\n", y[:5])

X shape: (400, 2)
y shape: (400, 1)
First 5 samples:
 [[-3.58724836 -3.09026238]
 [-1.82176593 -2.06919332]
 [-3.02076961 -2.76449604]
 [-2.46421129 -2.48077671]
 [-0.3628395  -0.43396924]]
First 5 labels:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [7]:
# Generate Uniform Data for 2 Classes

class0 = np.random.uniform(-4, -1, (200,2))
class1 = np.random.uniform(1, 4, (200,2))

X = np.vstack((class0, class1))
y = np.vstack((np.zeros((200,1)), np.ones((200,1))))
print("X shape:", X.shape) # (400, 2)
print("y shape:", y.shape) # (400, 1)   
print("First 5 samples:\n", X[:5])
print("First 5 labels:\n", y[:5])

X shape: (400, 2)
y shape: (400, 1)
First 5 samples:
 [[-2.96796947 -1.15510975]
 [-3.12228746 -3.26202818]
 [-2.25058606 -3.22589213]
 [-2.57984282 -1.49747123]
 [-3.30879906 -2.71992576]]
First 5 labels:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [9]:
# Generate Circular Data for 2 Classes

theta = np.linspace(0, 2*np.pi, 200)

r1 = 1
r2 = 3

class0 = np.c_[r1*np.cos(theta), r1*np.sin(theta)]
class1 = np.c_[r2*np.cos(theta), r2*np.sin(theta)]

X = np.vstack((class0, class1))
y = np.vstack((np.zeros((200,1)), np.ones((200,1))))

print("X shape:", X.shape) # (400, 2)
print("y shape:", y.shape) # (400, 1)   
print("First 5 samples:\n", X[:5])
print("First 5 labels:\n", y[:5])

X shape: (400, 2)
y shape: (400, 1)
First 5 samples:
 [[1.         0.        ]
 [0.99950159 0.03156855]
 [0.99800685 0.06310563]
 [0.99551728 0.09457981]
 [0.99203536 0.12595971]]
First 5 labels:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [10]:
# Generate XOR Data for 2 Classes

X = np.random.randn(400,2)
y = np.logical_xor(X[:,0] > 0, X[:,1] > 0).astype(int)
y = y.reshape(-1,1)
print("X shape:", X.shape) # (400, 2)
print("y shape:", y.shape) # (400, 1)   
print("First 5 samples:\n", X[:5])
print("First 5 labels:\n", y[:5])

X shape: (400, 2)
y shape: (400, 1)
First 5 samples:
 [[ 1.55701004  0.8840272 ]
 [-2.01954009 -0.984209  ]
 [-0.18779492  0.4869373 ]
 [-0.10665267 -0.49321439]
 [ 0.59530031  1.16415177]]
First 5 labels:
 [[0]
 [0]
 [1]
 [0]
 [0]]


In [11]:
# Imbalanced Data: 350 samples of Class 0 and 50 samples of Class 1

class0 = np.random.randn(350,2) + [-2,-2]
class1 = np.random.randn(50,2) + [2,2]

X = np.vstack((class0, class1))
y = np.vstack((np.zeros((350,1)), np.ones((50,1))))
print("X shape:", X.shape) # (400, 2)
print("y shape:", y.shape) # (400, 1)   
print("First 5 samples:\n", X[:5])
print("First 5 labels:\n", y[:5])

X shape: (400, 2)
y shape: (400, 1)
First 5 samples:
 [[-1.4444544  -1.56047768]
 [-1.69372751 -1.00085015]
 [-2.96606319  0.16001311]
 [-2.1003017  -2.70340009]
 [-1.697439   -0.90766112]]
First 5 labels:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [12]:
# Using Random Linear Boundary (General Method)

np.random.seed(0)

X = np.random.randn(400,2)

real_w = np.array([[1], [-2]])
bias = 0.5

z = X @ real_w + bias
y = (z > 0).astype(int)

print(z[:5])  # Print first 5 linear combinations
print(y[:5])  # Print first 5 labels

[[ 1.46373793]
 [-3.00304841]
 [ 4.32211375]
 [ 1.75280283]
 [-0.42441586]]
[[1]
 [0]
 [1]
 [1]
 [0]]


In [14]:
# Add Noise: Flip 10% of the labels randomly

noise_idx = np.random.choice(400, 40)  # flip 10% labels
y[noise_idx] = 1 - y[noise_idx]
print("First 5 labels:\n", y[:5])

First 5 labels:
 [[1]
 [0]
 [1]
 [1]
 [1]]


In [15]:
# Spiral Data for 2 Classes
n = 200
theta = np.sqrt(np.random.rand(n))*2*np.pi

r_a = 2*theta + np.pi
data_a = np.c_[np.cos(theta)*r_a, np.sin(theta)*r_a]

r_b = -2*theta - np.pi
data_b = np.c_[np.cos(theta)*r_b, np.sin(theta)*r_b]

X = np.vstack((data_a, data_b))
y = np.vstack((np.zeros((n,1)), np.ones((n,1))))

print("X shape:", X.shape) # (400, 2)
print("y shape:", y.shape) # (400, 1)   
print("First 5 samples:\n", X[:5])
print("First 5 labels:\n", y[:5])

X shape: (400, 2)
y shape: (400, 1)
First 5 samples:
 [[ -1.9701649  -12.08356565]
 [ -8.77786647  -5.97897815]
 [ -4.28575651   6.15454075]
 [  9.55037777 -10.31846766]
 [ 13.93870141  -5.44227643]]
First 5 labels:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [17]:
# 📌 np.random.rand() → Uniform [0,1)

import numpy as np

x = np.random.rand(5)        # 1D
x2 = np.random.rand(3,2)     # 2D
print("1D array:\n", x)
print("2D array:\n", x2)

1D array:
 [0.86711454 0.29426616 0.43535347 0.79545653 0.67750836]
2D array:
 [[0.93786437 0.62114033]
 [0.09781016 0.88436036]
 [0.76915552 0.71187045]]


In [18]:
# 📌 np.random.uniform(low, high, size)

x = np.random.uniform(5, 10, 5)
x2 = np.random.uniform(-2, 2, (3,2))
print("Uniform [5,10):\n", x)
print("Uniform [-2,2):\n", x2)

Uniform [5,10):
 [5.26866774 6.98111372 5.8371791  9.10951954 8.50264311]
Uniform [-2,2):
 [[ 1.53231039  1.86630043]
 [ 1.09899046  1.97693233]
 [ 0.45907954 -1.85148158]]


In [19]:
# 🎯 2️⃣ Normal (Gaussian) Distribution
# 📌 np.random.randn() → Mean=0, Std=1

x = np.random.randn(5)
x2 = np.random.randn(3,2)
print("Standard Normal (1D):\n", x)
print("Standard Normal (2D):\n", x2)

Standard Normal (1D):
 [ 0.22805333  0.20147995  0.54077359 -1.81807763 -0.04932407]
Standard Normal (2D):
 [[ 0.2390336  -1.00033035]
 [ 1.67398571  0.16155927]
 [ 1.56340475 -0.79052302]]


In [20]:
# 📌 np.random.normal(mean, std, size)

x = np.random.normal(10, 2, 5)
x2 = np.random.normal(0, 1, (4,3))
print("Normal (mean=10, std=2):\n", x)
print("Standard Normal (mean=0, std=1):\n", x2)

Normal (mean=10, std=2):
 [ 8.18539976 10.44850444  6.64262327 10.42993118 10.19443846]
Standard Normal (mean=0, std=1):
 [[ 1.01566528  0.70104134 -0.41747735]
 [-1.09749665  1.71230522 -0.79211502]
 [-1.04552456 -1.08485606  1.11730532]
 [-0.5189002  -0.75370447  0.13768983]]


In [21]:
# 🎯 4️⃣ Random Choice
# 📌 np.random.choice()

# From list
x1 = np.random.choice([0,1], 10)

# With probabilities
x2 = np.random.choice([0,1], 10, p=[0.8,0.2])

# Without replacement
x3 = np.random.choice(10, 5, replace=False)

print("Random choice from [0,1]:\n", x1)
print("Random choice with probabilities:\n", x2)    
print("Random choice without replacement:\n", x3)

Random choice from [0,1]:
 [1 0 0 1 0 0 0 1 1 0]
Random choice with probabilities:
 [0 0 0 0 0 1 0 0 0 0]
Random choice without replacement:
 [0 2 6 5 8]


In [22]:
# 🎯 5️⃣ Shuffle
# 📌 np.random.shuffle()

x = np.arange(10)
np.random.shuffle(x)
print("Shuffled array:\n", x)

Shuffled array:
 [3 1 0 6 2 8 5 4 7 9]


In [25]:
# 📌 np.random.permutation()

x = np.random.permutation(10)
print("Shuffled array (permutation):\n", x)

Shuffled array (permutation):
 [7 5 8 3 9 0 4 2 1 6]


In [26]:
# 🎯 6️⃣ Multivariate Normal (Advanced Gaussian)

mean = [0,0]
cov = [[1,0.8],[0.8,1]]

x = np.random.multivariate_normal(mean, cov, 200)
print("Multivariate Normal samples:\n", x[:5])

Multivariate Normal samples:
 [[-0.18310029 -0.23899388]
 [-0.21394389  0.02728493]
 [-0.06919533 -0.05886222]
 [-0.40108565 -0.13836322]
 [ 1.43075312  0.52634724]]


In [27]:
# 🎯 7️⃣ Binomial Distribution
x1 = np.random.binomial(n=10, p=0.5, size=5)

# 🎯 8️⃣ Bernoulli Distribution
x2 = np.random.binomial(1, 0.7, 10)

print("Binomial samples:\n", x1)
print("Bernoulli samples:\n", x2)

Binomial samples:
 [4 3 3 5 4]
Bernoulli samples:
 [1 0 1 1 0 0 1 1 1 1]


In [28]:
# 🎯 9️⃣ Exponential Distribution
x1 = np.random.exponential(scale=1.0, size=5)

# 🎯 🔟 Poisson Distribution
x2 = np.random.poisson(lam=3, size=5)

# 🎯 1️⃣1️⃣ Beta Distribution
x3  = np.random.beta(a=2, b=5, size=5)


# 🎯 1️⃣2️⃣ Gamma Distribution
x4 = np.random.gamma(shape=2, scale=2, size=5)

# 🎯 1️⃣3️⃣ Lognormal Distribution
x5 = np.random.lognormal(mean=0, sigma=1, size=5)

print("Exponential samples:\n", x1)
print("Poisson samples:\n", x2)
print("Beta samples:\n", x3)
print("Gamma samples:\n", x4)
print("Lognormal samples:\n", x5)

Exponential samples:
 [2.16737818 0.16021415 1.737215   0.01508954 0.61136205]
Poisson samples:
 [1 4 1 0 6]
Beta samples:
 [0.26958152 0.22421703 0.4386686  0.33116641 0.12169956]
Gamma samples:
 [1.40941526 6.87503658 1.11754168 0.76716741 1.43699429]
Lognormal samples:
 [5.90073    0.85097414 6.01615773 1.02789159 9.31863715]


In [29]:
# 🎯 1️⃣4️⃣ Random Bytes
x = np.random.bytes(10)
print("Random bytes:\n", x)

# 🎯 1️⃣5️⃣ Set Random Seed --> ✔ Reproducibility
np.random.seed(42)

Random bytes:
 b'\xbb\xac\xbf\xcf+\x0e^[\xcf\xa3'


In [30]:
rng = np.random.default_rng(42)

x = rng.normal(0,1,(5,2))
x2 = rng.uniform(0,10,5)
x3 = rng.integers(0,10,5)

print("Normal samples:\n", x)
print("Uniform samples:\n", x2)
print("Integer samples:\n", x3)

Normal samples:
 [[ 0.30471708 -1.03998411]
 [ 0.7504512   0.94056472]
 [-1.95103519 -1.30217951]
 [ 0.1278404  -0.31624259]
 [-0.01680116 -0.85304393]]
Uniform samples:
 [3.70798024 9.26764989 6.4386512  8.22761613 4.43414199]
Integer samples:
 [4 2 0 5 8]
